/**
 * Agent-service process lifecycle (GATE-3.5 A2, R09/R12/R13).
 *
 * Pure Node (no electron imports) so the spawn + authenticated-health
 * handshake can be unit/integration tested under vitest.
 *
 * Flow:
 *   1. Electron main generates one per-launch token (generateAuthToken).
 *   2. launchService spawns `python -m arsvox_agent --config <repo>/configs/app.yaml`
 *      with ARSVOX_AUTH_TOKEN=<token> in the child env and the repo's
 *      package roots prepended to PYTHONPATH.
 *   3. We poll GET /health until the service answers, then verify the
 *      token with an authenticated probe (GET /config, Bearer header):
 *      200 -> status "ready"; 401 -> "failed" (a foreign service holds
 *      the port with a different token — a cold launch must never
 *      silently adopt it).
 *   4. Child exit before ready -> "failed" with the stderr tail; after
 *      ready -> "stopped". terminate() (desktop quit) kills the process
 *      tree.
 *
 * serviceMode "auto" (default) first probes /health once: if something
 * already answers (e.g. a dev mock started by hand), we adopt it instead
 * of double-binding the port. "external" never spawns.
 */

import { spawn, spawnSync, type ChildProcess } from "node:child_process";
import * as crypto from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";

export type ServiceState = "starting" | "ready" | "failed" | "stopped";

export interface ServiceStatus {
  state: ServiceState;
  /** Human-readable (Spanish, UI locale) detail for failed/stopped. */
  detail?: string;
}

export interface LaunchOptions {
  /** Per-launch bearer token (generated by Electron main). */
  token: string;
  /** http://127.0.0.1:8765 by default; strip trailing slashes. */
  agentBaseUrl: string;
  /** Repo root; child cwd + PYTHONPATH/config resolution base. */
  repoRoot?: string;
  /** Python interpreter (env override wins; else repo venv, else python). */
  pythonPath?: string;
  /** Config file for the spawned service (default repo configs/app.yaml). */
  configPath?: string;
  serviceMode?: "auto" | "external";
  healthTimeoutMs?: number;
  healthIntervalMs?: number;
  /** Test seam: inject a fake spawner. */
  spawnFn?: (command: string, args: string[], options: unknown) => ChildProcess;
  onStatus: (status: ServiceStatus) => void;
}

export interface ServiceHandle {
  /** The spawned child (null in external mode or before spawn). */
  child: ChildProcess | null;
  /** True once terminate() has been requested. */
  terminated: boolean;
  /** Kill the child process tree; resolves when it is gone. */
  terminate: () => Promise<void>;
}

const delay = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));

/** 32 random bytes, base64url — never persisted, one per launch. */
export function generateAuthToken(): string {
  return crypto.randomBytes(32).toString("base64url");
}

/**
 * Resolve the Python interpreter for the child service:
 * 1. ARSVOX_PYTHON env override (always honored),
 * 2. the repo venv (WSL: .venv/bin/python, Windows: .venv/Scripts/python.exe),
 * 3. a bare `python`/`python3` from PATH.
 */
export function resolvePythonPath(repoRoot: string): string {
  const fromEnv = process.env.ARSVOX_PYTHON;
  if (fromEnv) return fromEnv;
  const candidates = [
    path.join(repoRoot, ".venv", "bin", "python"),
    path.join(repoRoot, ".venv", "Scripts", "python.exe"),
    process.platform === "win32" ? "python" : "python3",
  ];
  for (const candidate of candidates) {
    if (!candidate.includes(path.sep) || fs.existsSync(candidate)) return candidate;
  }
  return candidates[candidates.length - 1];
}

/** Repo roots the agent service imports from, in sys.path order. */
const SERVICE_PACKAGE_ROOTS = [
  "packages/contracts",
  "services/agent",
  "services/memory",
  "services/tts",
  "services/voice",
];

export function buildChildEnv(repoRoot: string, token: string): Record<string, string> {
  const roots = SERVICE_PACKAGE_ROOTS.map((rel) => path.join(repoRoot, rel));
  const existing = process.env.PYTHONPATH;
  return {
    ...(process.env as Record<string, string>),
    ARSVOX_AUTH_TOKEN: token,
    PYTHONPATH: existing ? `${roots.join(path.delimiter)}${path.delimiter}${existing}` : roots.join(path.delimiter),
    PYTHONUNBUFFERED: "1",
  };
}

async function probeHealthOnce(baseUrl: string): Promise<boolean> {
  try {
    const res = await fetch(`${baseUrl}/health`, { signal: AbortSignal.timeout(1500) });
    return res.ok;
  } catch {
    return false;
  }
}

type AuthProbe = "ok" | "unauthorized" | "error";

async function probeAuth(baseUrl: string, token: string): Promise<AuthProbe> {
  try {
    const res = await fetch(`${baseUrl}/config`, {
      headers: { Authorization: `Bearer ${token}` },
      signal: AbortSignal.timeout(3000),
    });
    if (res.status === 200) return "ok";
    if (res.status === 401) return "unauthorized";
    return "error";
  } catch {
    return "error";
  }
}

export function launchService(options: LaunchOptions): ServiceHandle {
  const repoRoot = options.repoRoot ?? defaultRepoRoot();
  const baseUrl = options.agentBaseUrl.replace(/\/+$/, "");

  const handle: ServiceHandle = {
    child: null,
    terminated: false,
    terminate: async () => {
      if (handle.terminated) return;
      handle.terminated = true;
      await killProcessTree(handle.child);
    },
  };

  let ready = false;
  let failed = false;
  const settleReady = (): void => {
    if (ready || failed || handle.terminated) return;
    ready = true;
    options.onStatus({ state: "ready" });
  };
  const settleFailed = (detail: string): void => {
    if (ready || failed || handle.terminated) return;
    failed = true;
    options.onStatus({ state: "failed", detail });
  };
  const notifyStopped = (detail: string): void => {
    // Deliberate terminate() suppresses the exit handler (handled below).
    if (handle.terminated) return;
    if (!ready || failed) return;
    options.onStatus({ state: "stopped", detail });
  };

  let stderrTail: string[] = [];

  const spawnService = (): void => {
    const python = options.pythonPath ?? resolvePythonPath(repoRoot);
    const configPath = options.configPath ?? path.join(repoRoot, "configs", "app.yaml");
    const spawnFn = options.spawnFn ?? spawn;
    const child = spawnFn(python, ["-m", "arsvox_agent", "--config", configPath], {
      cwd: repoRoot,
      env: buildChildEnv(repoRoot, options.token),
      windowsHide: true,
      stdio: ["ignore", "ignore", "pipe"],
    });
    handle.child = child;

    child.stderr?.on("data", (chunk: Buffer) => {
      const lines = chunk.toString("utf8").split("\n");
      stderrTail.push(...lines);
      if (stderrTail.length > 24) stderrTail = stderrTail.slice(-24);
    });

    child.on("error", (err: Error) => {
      handle.child = null;
      settleFailed(`no se pudo iniciar el proceso de servicio: ${err.message}`);
    });

    child.on("exit", (code, signal) => {
      handle.child = null;
      if (handle.terminated) return; // we killed it on quit
      const tail = stderrTail.join(" ").trim().slice(-400);
      if (!ready) {
        settleFailed(
          `el servicio terminó antes de estar listo (exit ${code ?? signal})${
            tail ? `: ${tail}` : ""
          }`,
        );
      } else {
        notifyStopped(`el servicio terminó (exit ${code ?? signal})`);
      }
    });
  };

  const pollUntilReady = async (): Promise<void> => {
    const timeoutMs = options.healthTimeoutMs ?? 30_000;
    const intervalMs = options.healthIntervalMs ?? 300;
    const deadline = Date.now() + timeoutMs;
    while (!handle.terminated) {
      if (await probeHealthOnce(baseUrl)) {
        await adoptService();
        return;
      }
      if (Date.now() >= deadline) {
        const tail = stderrTail.join(" ").trim().slice(-300);
        settleFailed(
          `el servicio no respondió en ${baseUrl} dentro de ${Math.round(timeoutMs / 1000)}s${
            tail ? `: ${tail}` : ""
          }`,
        );
        return;
      }
      await delay(intervalMs);
    }
  };

  const adoptService = async (): Promise<void> => {
    const probe = await probeAuth(baseUrl, options.token);
    if (probe === "ok") {
      settleReady();
      return;
    }
    if (probe === "unauthorized") {
      settleFailed(
        "un servicio ya está corriendo en el puerto pero rechazó el token de esta sesión " +
          "(¿lanzado con otro token?). Ciérralo y vuelve a abrir la aplicación.",
      );
      return;
    }
    settleFailed("el servicio respondió /health pero falló la verificación de autenticación");
  };

  void (async () => {
    if (options.serviceMode === "external") {
      await pollUntilReady();
      return;
    }
    // Auto mode: adopt an already-running service (dev mock started by
    // hand) instead of double-binding the port.
    if (await probeHealthOnce(baseUrl)) {
      await adoptService();
      return;
    }
    spawnService();
    await pollUntilReady();
  })();

  return handle;
}

async function killProcessTree(child: ChildProcess | null): Promise<void> {
  if (!child || child.pid === undefined) return;
  if (child.exitCode !== null || child.signalCode !== null) return;
  const exited = new Promise<void>((resolve) => {
    child.once("exit", () => resolve());
  });
  if (process.platform === "win32") {
    // taskkill /T kills the whole tree (uvicorn + any worker children).
    try {
      spawnSync("taskkill", ["/pid", String(child.pid), "/T", "/F"], {
        windowsHide: true,
        stdio: "ignore",
      });
    } catch {
      child.kill();
    }
  } else {
    child.kill("SIGTERM");
  }
  await Promise.race([exited, delay(3000)]);
  if (child.exitCode === null && child.signalCode === null) {
    child.kill("SIGKILL");
    await Promise.race([exited, delay(1000)]);
  }
}

/** Repo root relative to the compiled main process (dist-electron/). */
function defaultRepoRoot(): string {
  const base = typeof __dirname !== "undefined" ? __dirname : process.cwd();
  return path.resolve(base, "..", "..");
}
