"""Ars-Vox wire contracts.

Every message that crosses a process boundary (WebSocket events, UI
commands, client messages, application config) is defined here as a
pydantic model. This package is the single source of truth:

  * services/* validate everything with these models,
  * scripts/export_schemas.py emits JSON Schema (packages/contracts/schemas),
  * the Electron UI mirrors these types in apps/desktop/src/types.ts.

Add or change a message shape here first, then regenerate schemas.
"""

from arsvox_contracts.adaptive import (
    ASSIGNABLE_ROLES,
    EQUAL_SPLIT_TEMPLATES,
    TEMPLATE_SLOTS,
    AdaptiveTemplate,
    LayoutAssignment,
    LayoutSpec,
    Proportion,
    SurfaceRegistration,
    SurfaceRole,
    validate_layout_spec,
)
from arsvox_contracts.client_messages import (
    CancelMessage,
    ClientAction,
    ClientMessage,
    ConfirmMessage,
    PingMessage,
    StopMessage,
    UiCommandMessage,
    UserText,
    parse_client_message,
)
from arsvox_contracts.commands import (
    AudioPlay,
    LayoutApply,
    LayoutRestore,
    LayoutSlots,
    MediaStateChange,
    NotificationShow,
    PanelClose,
    PanelFullscreen,
    PanelOpen,
    PanelSetPrimary,
    TtsSpeak,
    UiCommand,
)
from arsvox_contracts.config import (
    AgentSection,
    AppConfig,
    BrowserSection,
    DemoSection,
    MediaSection,
    MemorySection,
    ModelSection,
    RemindersSection,
    ServerSection,
    TelegramSection,
    TtsSection,
    UiSection,
    VoiceSection,
)
from arsvox_contracts.enums import (
    ConfirmationStatus,
    EventType,
    LayoutRole,
    LayoutTemplate,
    MediaState,
    NotificationKind,
    NotificationStatus,
    PanelType,
    PolicyKind,
    ReminderStatus,
    TaskStatus,
    VoiceState,
)
from arsvox_contracts.events import (
    ActionResultEvent,
    AgentEvent,
    AgentMessageEvent,
    ConfigUpdateEvent,
    ConfirmationRequestedEvent,
    ConfirmationResolvedEvent,
    ErrorEvent,
    NotificationEvent,
    PongEvent,
    StateUpdateEvent,
    ToolCallEvent,
    UiCommandEvent,
    UserMessageEvent,
)

__all__ = [
    "ASSIGNABLE_ROLES",
    "ActionResultEvent",
    "AdaptiveTemplate",
    "AgentEvent",
    "AgentMessageEvent",
    "AgentSection",
    "AppConfig",
    "AudioPlay",
    "BrowserSection",
    "CancelMessage",
    "ClientAction",
    "ClientMessage",
    "ConfigUpdateEvent",
    "ConfirmationRequestedEvent",
    "ConfirmationResolvedEvent",
    "ConfirmationStatus",
    "DemoSection",
    "EQUAL_SPLIT_TEMPLATES",
    "ErrorEvent",
    "EventType",
    "LayoutApply",
    "LayoutAssignment",
    "LayoutRestore",
    "LayoutRole",
    "LayoutSlots",
    "LayoutSpec",
    "LayoutTemplate",
    "MediaSection",
    "MediaState",
    "MediaStateChange",
    "MemorySection",
    "ModelSection",
    "NotificationEvent",
    "NotificationKind",
    "NotificationShow",
    "NotificationStatus",
    "PanelClose",
    "PanelFullscreen",
    "PanelOpen",
    "PanelSetPrimary",
    "PanelType",
    "PingMessage",
    "PolicyKind",
    "PongEvent",
    "Proportion",
    "ReminderStatus",
    "RemindersSection",
    "ServerSection",
    "StateUpdateEvent",
    "StopMessage",
    "SurfaceRegistration",
    "SurfaceRole",
    "TEMPLATE_SLOTS",
    "TaskStatus",
    "TelegramSection",
    "ToolCallEvent",
    "TtsSection",
    "TtsSpeak",
    "UiCommand",
    "UiCommandEvent",
    "UiCommandMessage",
    "UiSection",
    "UserMessageEvent",
    "UserText",
    "VoiceSection",
    "VoiceState",
    "parse_client_message",
    "validate_layout_spec",
]
